# Generated by Django 4.1.4 on 2023-06-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navbar',
            new_name='NavbarItem',
        ),
    ]
