# Generated by Django 4.1.4 on 2023-06-18 06:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_navbar_navbaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Интро',
                'verbose_name_plural': 'Интро',
                'db_table': 'landing_intro',
            },
        ),
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
