# Generated by Django 4.1.4 on 2023-06-18 07:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_service_servicesblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('sorting_order', models.IntegerField(default=1, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Список преимуществ',
                'db_table': 'landing_advantage',
            },
        ),
        migrations.CreateModel(
            name='AdvantageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
                'db_table': 'landing_advantages',
            },
        ),
    ]
