# Generated by Django 4.1.4 on 2023-06-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_advantage_advantageblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='image',
        ),
    ]
