# Generated by Django 4.1.4 on 2023-06-18 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_remove_advantage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('privacy_policy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Политика конфиденциальности')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Расчёт стоимости',
                'verbose_name_plural': 'Расчёт стоимости',
                'db_table': 'landing_cost_calculation',
            },
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Список преимуществ'},
        ),
    ]
