# Generated by Django 4.1.4 on 2023-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_costcalculation_alter_advantage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcalculation',
            name='privacy_policy_href',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
