# Generated by Django 4.1.4 on 2023-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_costcalculation_privacy_policy_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcalculation',
            name='privacy_policy_href',
        ),
    ]
