# Generated by Django 4.1.4 on 2023-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_remove_costcalculation_privacy_policy_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('yandex_iframe_src', models.CharField(max_length=1000, verbose_name='Яндекс карта (iframe src)')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'db_table': 'landing_contacts',
            },
        ),
    ]
