# Generated by Django 4.1.4 on 2023-06-18 09:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страница'},
        ),
        migrations.AlterField(
            model_name='page',
            name='cost_calculation_header',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, verbose_name='Заголовок Расчет стоимости'),
        ),
    ]
