# Generated by Django 4.1.4 on 2023-06-18 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_delete_about_delete_advantageblock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='page',
            name='about_header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='advantage_header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='contact_header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cost_calculation_header',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cost_calculation_image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cost_calculation_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro_header',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro_image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='service_header',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
