# Generated by Django 4.1.4 on 2023-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_alter_advantage_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cost_calculation_image',
            field=models.ImageField(upload_to='costcalc_img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro_image',
            field=models.ImageField(upload_to='intro_img/', verbose_name='Изображение'),
        ),
    ]
