# Generated by Django 4.1.4 on 2023-06-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_page_cost_calculation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='favicon/', verbose_name='Favicon')),
                ('copyright', models.CharField(max_length=255, verbose_name='Копирайт в футере')),
            ],
            options={
                'verbose_name': 'Прочее',
                'verbose_name_plural': 'Прочее',
                'db_table': 'landing_general',
            },
        ),
    ]
