# Generated by Django 4.1.4 on 2023-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Копирайт в футере'),
        ),
    ]
