# Generated by Django 4.1.4 on 2023-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_remove_page_copyright'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='sorting_order',
            field=models.IntegerField(default=1, verbose_name='Порядок сортировки'),
        ),
    ]
