# Generated by Django 4.1.4 on 2022-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jsonobject_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonobject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
