# Generated by Django 4.1.4 on 2023-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jsonobject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм id')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
            },
        ),
    ]
