# Generated by Django 4.1.4 on 2023-01-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_datetimesettings_alter_jsonobject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование маркетплейса')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование склада')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес склада')),
                ('opening_hours', models.CharField(blank=True, max_length=500, null=True, verbose_name='График работы склада')),
                ('how_to_get_there', models.TextField(blank=True, null=True, verbose_name='Как добраться до склада')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Склад маркетплейса',
                'verbose_name_plural': 'Склады маркетплейса',
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование пункта выдачи')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес пункта выдачи')),
                ('opening_hours', models.CharField(blank=True, max_length=500, null=True, verbose_name='График работы до пункта выдачи')),
                ('how_to_get_there', models.TextField(blank=True, null=True, verbose_name='Как добраться до пункта выдачи')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'ПВЗ маркетплейса',
                'verbose_name_plural': 'ПВЗ маркетплейса',
                'db_table': 'app_pickup_point',
            },
        ),
    ]
