# Generated by Django 4.1.4 on 2023-01-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_marketplace_warehouse_pickuppoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'verbose_name': 'ПВЗ', 'verbose_name_plural': 'ПВЗ'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_pickup_point', to='app.marketplace', verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='График работы пункта выдачи'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_warehouse', to='app.marketplace', verbose_name='Маркетплейс'),
        ),
    ]
