# Generated by Django 4.1.4 on 2023-01-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pickuppoint_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='app.marketplace', verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='app.marketplace', verbose_name='Маркетплейс'),
        ),
    ]
