# Generated by Django 4.1.4 on 2023-01-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pickuppoint_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=200, verbose_name='Функция-обработчик')),
                ('html_file', models.CharField(max_length=200, verbose_name='HTML файл')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование страницы')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('body', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тело страницы')),
            ],
        ),
    ]
