# Generated by Django 4.1.4 on 2023-01-30 11:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_page_options_alter_page_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тэг title'),
        ),
    ]
