# Generated by Django 4.1.4 on 2023-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_page_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Тэг title'),
            preserve_default=False,
        ),
    ]
