# Generated by Django 4.1.4 on 2023-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profile_inn_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
