# Generated by Django 4.1.4 on 2023-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_custompagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompagemodel',
            options={'verbose_name': 'Загрузка договора-оферты', 'verbose_name_plural': 'Загрузка договора-оферты'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='supply_dates',
            field=models.JSONField(default='[]', verbose_name='Даты поставок'),
        ),
    ]
