# Generated by Django 4.1.4 on 2023-02-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_warehouse_supply_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='supply_dates',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Даты поставок'),
        ),
    ]
