# Generated by Django 4.1.4 on 2023-02-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_customadminpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPageModel',
        ),
        migrations.AlterModelOptions(
            name='customadminpage',
            options={'verbose_name': 'Хрень', 'verbose_name_plural': 'Хрень'},
        ),
    ]
