# Generated by Django 4.1.4 on 2023-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_custompagemodel_alter_customadminpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес пункта выдачи'),
        ),
    ]
