# Generated by Django 4.1.4 on 2023-04-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_newuser_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
