# Generated by Django 4.1.4 on 2023-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_profile_options_page_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sorting_order',
            field=models.IntegerField(default=1, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='handler',
            field=models.CharField(max_length=200, verbose_name='Функция-обработчик = url'),
        ),
    ]
