# Generated by Django 4.1.4 on 2023-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_page_sorting_order_alter_page_handler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sorting_order'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
    ]
