# Generated by Django 4.1.4 on 2023-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_page_options_alter_page_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показ в меню'),
        ),
    ]
