# Generated by Django 4.1.4 on 2023-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_page_name_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_data_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Принятие договора-оферты'),
        ),
    ]
