# Generated by Django 4.1.4 on 2023-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_profile_personal_data_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_added_to_main_system',
            field=models.BooleanField(default=False, verbose_name='ЛК активирован?'),
        ),
    ]
