# Generated by Django 4.1.4 on 2023-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_profile_is_added_to_main_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moysklad_counterparty_id',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='id контрагента в МойСклад'),
        ),
    ]
