# Generated by Django 4.1.4 on 2023-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_profile_moysklad_counterparty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='moysklad_counterparty_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='id контрагента в МойСклад'),
        ),
    ]
