# Generated by Django 4.1.4 on 2023-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_supplywarehousecompany_sypplytype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyorder',
            options={'verbose_name': 'Поставка: Заказ', 'verbose_name_plural': 'Поставка: Заказы'},
        ),
        migrations.AlterModelOptions(
            name='supplywarehouse',
            options={'verbose_name': 'Поставка: Склад', 'verbose_name_plural': 'Поставка: Склады'},
        ),
        migrations.AlterModelOptions(
            name='supplywarehousecompany',
            options={'verbose_name': 'Поставка: Компания', 'verbose_name_plural': 'Поставка: Компании'},
        ),
        migrations.AlterModelOptions(
            name='sypplytype',
            options={'verbose_name': 'Поставка: Тип', 'verbose_name_plural': 'Поставка: Типы'},
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='recipient_full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='recipient_phone_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона получателя'),
        ),
    ]
