# Generated by Django 4.1.4 on 2023-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_supplyorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Наименование компании')),
                ('warehouse', models.CharField(default='Основной склад', max_length=255)),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'db_table': 'app_company_settings',
            },
        ),
    ]
