# Generated by Django 4.1.4 on 2023-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='warehouse',
            field=models.CharField(default='', max_length=255, verbose_name='Основной склад'),
        ),
    ]
