# Generated by Django 4.1.4 on 2023-04-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Компания: инфо', 'verbose_name_plural': 'Компания: инфо'},
        ),
        migrations.AlterModelOptions(
            name='companywarehouse',
            options={'verbose_name': 'Компания: склад', 'verbose_name_plural': 'Компания: склады'},
        ),
    ]
