# Generated by Django 4.1.4 on 2023-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Компания'),
        ),
    ]
