# Generated by Django 4.1.4 on 2023-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон'),
        ),
    ]
